project:
  type: website
  output-dir: docs

website:
  title: "Migs Germar's Data Science Blog"
  favicon: posts/images/favicon.ico
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/MiguelAHG
      - icon: linkedin
        href: https://www.linkedin.com/in/migs-germar/
      - icon: facebook
        href: https://www.facebook.com/miguelantonio.germar
  comments:
    giscus:
      repo: MiguelAHG/migs-germar-data-science-blog
      repo-id: R_kgDOJySw9w
      category: Announcements
      category-id: DIC_kwDOJySw984CXXr6
      mapping: pathname
      reactions-enabled: true
      loading: lazy
      input-position: top
      theme: light
      language: en
  google-analytics: "G-99SLFW8P3J"
format:
  html:
    theme: cosmo
    css: styles.css



