<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Migs Germar">
<meta name="dcterms.date" content="2021-06-01">
<meta name="description" content="I use intermediate Pandas techniques in cleaning and analyzing employee exit surveys from Australian government institutes.">

<title>Migs Germar’s Data Science Blog - Employee Exit Survey Data Cleaning and Aggregation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../posts/images/favicon.ico" rel="icon">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Migs Germar’s Data Science Blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/MiguelAHG" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/migs-germar/" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.facebook.com/miguelantonio.germar" rel="" target=""><i class="bi bi-facebook" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Employee Exit Survey Data Cleaning and Aggregation</h1>
                  <div>
        <div class="description">
          I use intermediate Pandas techniques in cleaning and analyzing employee exit surveys from Australian government institutes.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">python</div>
                <div class="quarto-category">pandas</div>
                <div class="quarto-category">matplotlib</div>
                <div class="quarto-category">seaborn</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Migs Germar </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">June 1, 2021</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#package-installs" id="toc-package-installs" class="nav-link" data-scroll-target="#package-installs">Package Installs</a></li>
  <li><a href="#data-overview" id="toc-data-overview" class="nav-link" data-scroll-target="#data-overview">Data Overview</a>
  <ul class="collapse">
  <li><a href="#tafe-survey" id="toc-tafe-survey" class="nav-link" data-scroll-target="#tafe-survey">TAFE Survey</a>
  <ul class="collapse">
  <li><a href="#columns" id="toc-columns" class="nav-link" data-scroll-target="#columns">Columns</a></li>
  <li><a href="#descriptive-statistics" id="toc-descriptive-statistics" class="nav-link" data-scroll-target="#descriptive-statistics">Descriptive Statistics</a></li>
  </ul></li>
  <li><a href="#dete-survey" id="toc-dete-survey" class="nav-link" data-scroll-target="#dete-survey">DETE Survey</a>
  <ul class="collapse">
  <li><a href="#columns-1" id="toc-columns-1" class="nav-link" data-scroll-target="#columns-1">Columns</a></li>
  <li><a href="#descriptive-statistics-1" id="toc-descriptive-statistics-1" class="nav-link" data-scroll-target="#descriptive-statistics-1">Descriptive Statistics</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#data-cleaning" id="toc-data-cleaning" class="nav-link" data-scroll-target="#data-cleaning">Data Cleaning</a>
  <ul class="collapse">
  <li><a href="#placeholders-for-missing-values" id="toc-placeholders-for-missing-values" class="nav-link" data-scroll-target="#placeholders-for-missing-values">Placeholders for Missing Values</a></li>
  <li><a href="#dropping-columns" id="toc-dropping-columns" class="nav-link" data-scroll-target="#dropping-columns">Dropping Columns</a></li>
  <li><a href="#matching-columns-in-tafe-and-dete" id="toc-matching-columns-in-tafe-and-dete" class="nav-link" data-scroll-target="#matching-columns-in-tafe-and-dete">Matching Columns in TAFE and DETE</a></li>
  <li><a href="#identifying-employees-who-resigned" id="toc-identifying-employees-who-resigned" class="nav-link" data-scroll-target="#identifying-employees-who-resigned">Identifying Employees who Resigned</a></li>
  <li><a href="#date-columns" id="toc-date-columns" class="nav-link" data-scroll-target="#date-columns">Date Columns</a></li>
  <li><a href="#years-of-service" id="toc-years-of-service" class="nav-link" data-scroll-target="#years-of-service">Years of Service</a></li>
  <li><a href="#contributing-factors-columns" id="toc-contributing-factors-columns" class="nav-link" data-scroll-target="#contributing-factors-columns">“Contributing Factors” Columns</a></li>
  <li><a href="#identifying-dissatisfaction" id="toc-identifying-dissatisfaction" class="nav-link" data-scroll-target="#identifying-dissatisfaction">Identifying Dissatisfaction</a></li>
  <li><a href="#combining-dete-and-tafe" id="toc-combining-dete-and-tafe" class="nav-link" data-scroll-target="#combining-dete-and-tafe">Combining DETE and TAFE</a></li>
  <li><a href="#cleaning-age-data" id="toc-cleaning-age-data" class="nav-link" data-scroll-target="#cleaning-age-data">Cleaning Age Data</a></li>
  <li><a href="#categorizing-years-of-service" id="toc-categorizing-years-of-service" class="nav-link" data-scroll-target="#categorizing-years-of-service">Categorizing Years of Service</a>
  <ul class="collapse">
  <li><a href="#extracting-numbers" id="toc-extracting-numbers" class="nav-link" data-scroll-target="#extracting-numbers">Extracting Numbers</a></li>
  <li><a href="#mapping-numbers-to-categories" id="toc-mapping-numbers-to-categories" class="nav-link" data-scroll-target="#mapping-numbers-to-categories">Mapping Numbers to Categories</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#data-analysis" id="toc-data-analysis" class="nav-link" data-scroll-target="#data-analysis">Data Analysis</a>
  <ul class="collapse">
  <li><a href="#dissatisfaction-by-age-group" id="toc-dissatisfaction-by-age-group" class="nav-link" data-scroll-target="#dissatisfaction-by-age-group">Dissatisfaction by Age Group</a></li>
  <li><a href="#dissatisfaction-by-career-stage" id="toc-dissatisfaction-by-career-stage" class="nav-link" data-scroll-target="#dissatisfaction-by-career-stage">Dissatisfaction by Career Stage</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/2021-06-01-queensland-australia.jpg" class="img-fluid figure-img"></p>
</figure>
</div>
<center>
<a href="https://unsplash.com/photos/ax7oet4UkRM">Unsplash | Kon Karampelas</a>
</center>
<section id="overview" class="level1">
<h1>Overview</h1>
<p>This project deals with messy data from employee exit surveys from 2 government institutions in Queensland, Australia:</p>
<ul>
<li>Department of Education, Training and Employment (DETE)</li>
<li>Technical and Further Education (TAFE)</li>
</ul>
<p>The project aims to determine what percentage of the resignees was dissatisfied with work:</p>
<ul>
<li>based on age group</li>
<li>based on career stage</li>
</ul>
<p>On the technical side, this project is intended to showcase the use of several intermediate Pandas techniques for data cleaning and manipulation, including vectorized methods, mapping functions across data, dropping rows and columns, and combining DataFrames.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>I wrote this notebook for the <a href="https://www.dataquest.io/">Dataquest</a> course’s <a href="https://app.dataquest.io/m/348/guided-project%3A-clean-and-analyze-employee-exit-surveys/11/next-steps">Guided Project: Clean and Analyze Employee Exit Surveys</a>. The general project flow and research questions came from Dataquest. However, all of the text and code here are written by me unless stated otherwise.</p>
</div>
</div>
</section>
<section id="package-installs" class="level1">
<h1>Package Installs</h1>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-overview" class="level1">
<h1>Data Overview</h1>
<section id="tafe-survey" class="level2">
<h2 class="anchored" data-anchor-id="tafe-survey">TAFE Survey</h2>
<p>The TAFE employee exit survey data can be found <a href="https://data.gov.au/dataset/ds-qld-89970a3b-182b-41ea-aea2-6f9f17b5907e/details?q=exit%20survey">here</a>.</p>
<p>Unfortunately, the CSV file itself is no longer available on the Australian government’s websites, so I used a copy that I downloaded from Dataquest.</p>
<section id="columns" class="level3">
<h3 class="anchored" data-anchor-id="columns">Columns</h3>
<p>Below is information about the TAFE columns.</p>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>tafe <span class="op">=</span> pd.read_csv(<span class="st">"./private/2021-06-01-EES-Files/tafe_survey.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>tafe.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 702 entries, 0 to 701
Data columns (total 72 columns):
 #   Column                                                                                                                                                         Non-Null Count  Dtype  
---  ------                                                                                                                                                         --------------  -----  
 0   Record ID                                                                                                                                                      702 non-null    float64
 1   Institute                                                                                                                                                      702 non-null    object 
 2   WorkArea                                                                                                                                                       702 non-null    object 
 3   CESSATION YEAR                                                                                                                                                 695 non-null    float64
 4   Reason for ceasing employment                                                                                                                                  701 non-null    object 
 5   Contributing Factors. Career Move - Public Sector                                                                                                              437 non-null    object 
 6   Contributing Factors. Career Move - Private Sector                                                                                                             437 non-null    object 
 7   Contributing Factors. Career Move - Self-employment                                                                                                            437 non-null    object 
 8   Contributing Factors. Ill Health                                                                                                                               437 non-null    object 
 9   Contributing Factors. Maternity/Family                                                                                                                         437 non-null    object 
 10  Contributing Factors. Dissatisfaction                                                                                                                          437 non-null    object 
 11  Contributing Factors. Job Dissatisfaction                                                                                                                      437 non-null    object 
 12  Contributing Factors. Interpersonal Conflict                                                                                                                   437 non-null    object 
 13  Contributing Factors. Study                                                                                                                                    437 non-null    object 
 14  Contributing Factors. Travel                                                                                                                                   437 non-null    object 
 15  Contributing Factors. Other                                                                                                                                    437 non-null    object 
 16  Contributing Factors. NONE                                                                                                                                     437 non-null    object 
 17  Main Factor. Which of these was the main factor for leaving?                                                                                                   113 non-null    object 
 18  InstituteViews. Topic:1. I feel the senior leadership had a clear vision and direction                                                                         608 non-null    object 
 19  InstituteViews. Topic:2. I was given access to skills training to help me do my job better                                                                     613 non-null    object 
 20  InstituteViews. Topic:3. I was given adequate opportunities for personal development                                                                           610 non-null    object 
 21  InstituteViews. Topic:4. I was given adequate opportunities for promotion within %Institute]Q25LBL%                                                            608 non-null    object 
 22  InstituteViews. Topic:5. I felt the salary for the job was right for the responsibilities I had                                                                615 non-null    object 
 23  InstituteViews. Topic:6. The organisation recognised when staff did good work                                                                                  607 non-null    object 
 24  InstituteViews. Topic:7. Management was generally supportive of me                                                                                             614 non-null    object 
 25  InstituteViews. Topic:8. Management was generally supportive of my team                                                                                        608 non-null    object 
 26  InstituteViews. Topic:9. I was kept informed of the changes in the organisation which would affect me                                                          610 non-null    object 
 27  InstituteViews. Topic:10. Staff morale was positive within the Institute                                                                                       602 non-null    object 
 28  InstituteViews. Topic:11. If I had a workplace issue it was dealt with quickly                                                                                 601 non-null    object 
 29  InstituteViews. Topic:12. If I had a workplace issue it was dealt with efficiently                                                                             597 non-null    object 
 30  InstituteViews. Topic:13. If I had a workplace issue it was dealt with discreetly                                                                              601 non-null    object 
 31  WorkUnitViews. Topic:14. I was satisfied with the quality of the management and supervision within my work unit                                                609 non-null    object 
 32  WorkUnitViews. Topic:15. I worked well with my colleagues                                                                                                      605 non-null    object 
 33  WorkUnitViews. Topic:16. My job was challenging and interesting                                                                                                607 non-null    object 
 34  WorkUnitViews. Topic:17. I was encouraged to use my initiative in the course of my work                                                                        610 non-null    object 
 35  WorkUnitViews. Topic:18. I had sufficient contact with other people in my job                                                                                  613 non-null    object 
 36  WorkUnitViews. Topic:19. I was given adequate support and co-operation by my peers to enable me to do my job                                                   609 non-null    object 
 37  WorkUnitViews. Topic:20. I was able to use the full range of my skills in my job                                                                               609 non-null    object 
 38  WorkUnitViews. Topic:21. I was able to use the full range of my abilities in my job. ; Category:Level of Agreement; Question:YOUR VIEWS ABOUT YOUR WORK UNIT]  608 non-null    object 
 39  WorkUnitViews. Topic:22. I was able to use the full range of my knowledge in my job                                                                            608 non-null    object 
 40  WorkUnitViews. Topic:23. My job provided sufficient variety                                                                                                    611 non-null    object 
 41  WorkUnitViews. Topic:24. I was able to cope with the level of stress and pressure in my job                                                                    610 non-null    object 
 42  WorkUnitViews. Topic:25. My job allowed me to balance the demands of work and family to my satisfaction                                                        611 non-null    object 
 43  WorkUnitViews. Topic:26. My supervisor gave me adequate personal recognition and feedback on my performance                                                    606 non-null    object 
 44  WorkUnitViews. Topic:27. My working environment was satisfactory e.g. sufficient space, good lighting, suitable seating and working area                       610 non-null    object 
 45  WorkUnitViews. Topic:28. I was given the opportunity to mentor and coach others in order for me to pass on my skills and knowledge prior to my cessation date  609 non-null    object 
 46  WorkUnitViews. Topic:29. There was adequate communication between staff in my unit                                                                             603 non-null    object 
 47  WorkUnitViews. Topic:30. Staff morale was positive within my work unit                                                                                         606 non-null    object 
 48  Induction. Did you undertake Workplace Induction?                                                                                                              619 non-null    object 
 49  InductionInfo. Topic:Did you undertake a Corporate Induction?                                                                                                  432 non-null    object 
 50  InductionInfo. Topic:Did you undertake a Institute Induction?                                                                                                  483 non-null    object 
 51  InductionInfo. Topic: Did you undertake Team Induction?                                                                                                        440 non-null    object 
 52  InductionInfo. Face to Face Topic:Did you undertake a Corporate Induction; Category:How it was conducted?                                                      555 non-null    object 
 53  InductionInfo. On-line Topic:Did you undertake a Corporate Induction; Category:How it was conducted?                                                           555 non-null    object 
 54  InductionInfo. Induction Manual Topic:Did you undertake a Corporate Induction?                                                                                 555 non-null    object 
 55  InductionInfo. Face to Face Topic:Did you undertake a Institute Induction?                                                                                     530 non-null    object 
 56  InductionInfo. On-line Topic:Did you undertake a Institute Induction?                                                                                          555 non-null    object 
 57  InductionInfo. Induction Manual Topic:Did you undertake a Institute Induction?                                                                                 553 non-null    object 
 58  InductionInfo. Face to Face Topic: Did you undertake Team Induction; Category?                                                                                 555 non-null    object 
 59  InductionInfo. On-line Topic: Did you undertake Team Induction?process you undertook and how it was conducted.]                                                555 non-null    object 
 60  InductionInfo. Induction Manual Topic: Did you undertake Team Induction?                                                                                       555 non-null    object 
 61  Workplace. Topic:Did you and your Manager develop a Performance and Professional Development Plan (PPDP)?                                                      608 non-null    object 
 62  Workplace. Topic:Does your workplace promote a work culture free from all forms of unlawful discrimination?                                                    594 non-null    object 
 63  Workplace. Topic:Does your workplace promote and practice the principles of employment equity?                                                                 587 non-null    object 
 64  Workplace. Topic:Does your workplace value the diversity of its employees?                                                                                     586 non-null    object 
 65  Workplace. Topic:Would you recommend the Institute as an employer to others?                                                                                   581 non-null    object 
 66  Gender. What is your Gender?                                                                                                                                   596 non-null    object 
 67  CurrentAge. Current Age                                                                                                                                        596 non-null    object 
 68  Employment Type. Employment Type                                                                                                                               596 non-null    object 
 69  Classification. Classification                                                                                                                                 596 non-null    object 
 70  LengthofServiceOverall. Overall Length of Service at Institute (in years)                                                                                      596 non-null    object 
 71  LengthofServiceCurrent. Length of Service at current workplace (in years)                                                                                      596 non-null    object 
dtypes: float64(2), object(70)
memory usage: 395.0+ KB</code></pre>
</div>
</div>
<p>The formatting is different because some column names are apparently too long. However, we can see that:</p>
<ul>
<li>There are 702 rows and 72 columns.</li>
<li>A few columns contain decimals, and most contain text.</li>
<li>Many of the columns have missing values.</li>
</ul>
<p>Dataquest notes a few columns in this dataset:</p>
<ul>
<li>“<code>Record ID</code>: An id used to identify the participant of the survey”</li>
<li>“<code>Reason for ceasing employment</code>: The reason why the person’s employment ended”</li>
<li>“<code>LengthofServiceOverall. Overall Length of Service at Institute (in years)</code>: The length of the person’s employment (in years)”</li>
</ul>
<p>Additionally, there are groups of columns that all start with the same name. These group names are:</p>
<ul>
<li>Contributing Factors</li>
<li>Institute Views</li>
<li>Work Unit Views</li>
<li>Induction Info</li>
<li>Workplace</li>
</ul>
<p>Currently, there are too many columns for analysis. However, since the Contributing Factors columns are directly related to the employee’s resignation, we could just keep those and remove the other 4 groups of columns.</p>
</section>
<section id="descriptive-statistics" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-statistics">Descriptive Statistics</h3>
<p>Below are descriptive statistics for the columns.</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>tafe.describe(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    include <span class="op">=</span> <span class="st">"all"</span>,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    datetime_is_numeric <span class="op">=</span> <span class="va">True</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Record ID</th>
<th data-quarto-table-cell-role="th">Institute</th>
<th data-quarto-table-cell-role="th">WorkArea</th>
<th data-quarto-table-cell-role="th">CESSATION YEAR</th>
<th data-quarto-table-cell-role="th">Reason for ceasing employment</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Career Move - Public Sector</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Career Move - Private Sector</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Career Move - Self-employment</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Ill Health</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Maternity/Family</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">Workplace. Topic:Does your workplace promote a work culture free from all forms of unlawful discrimination?</th>
<th data-quarto-table-cell-role="th">Workplace. Topic:Does your workplace promote and practice the principles of employment equity?</th>
<th data-quarto-table-cell-role="th">Workplace. Topic:Does your workplace value the diversity of its employees?</th>
<th data-quarto-table-cell-role="th">Workplace. Topic:Would you recommend the Institute as an employer to others?</th>
<th data-quarto-table-cell-role="th">Gender. What is your Gender?</th>
<th data-quarto-table-cell-role="th">CurrentAge. Current Age</th>
<th data-quarto-table-cell-role="th">Employment Type. Employment Type</th>
<th data-quarto-table-cell-role="th">Classification. Classification</th>
<th data-quarto-table-cell-role="th">LengthofServiceOverall. Overall Length of Service at Institute (in years)</th>
<th data-quarto-table-cell-role="th">LengthofServiceCurrent. Length of Service at current workplace (in years)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>7.020000e+02</td>
<td>702</td>
<td>702</td>
<td>695.000000</td>
<td>701</td>
<td>437</td>
<td>437</td>
<td>437</td>
<td>437</td>
<td>437</td>
<td>...</td>
<td>594</td>
<td>587</td>
<td>586</td>
<td>581</td>
<td>596</td>
<td>596</td>
<td>596</td>
<td>596</td>
<td>596</td>
<td>596</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">unique</td>
<td>NaN</td>
<td>12</td>
<td>2</td>
<td>NaN</td>
<td>6</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>...</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>2</td>
<td>9</td>
<td>5</td>
<td>9</td>
<td>7</td>
<td>7</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">top</td>
<td>NaN</td>
<td>Brisbane North Institute of TAFE</td>
<td>Non-Delivery (corporate)</td>
<td>NaN</td>
<td>Resignation</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>...</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
<td>Female</td>
<td>56 or older</td>
<td>Permanent Full-time</td>
<td>Administration (AO)</td>
<td>Less than 1 year</td>
<td>Less than 1 year</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">freq</td>
<td>NaN</td>
<td>161</td>
<td>432</td>
<td>NaN</td>
<td>340</td>
<td>375</td>
<td>336</td>
<td>420</td>
<td>403</td>
<td>411</td>
<td>...</td>
<td>536</td>
<td>512</td>
<td>488</td>
<td>416</td>
<td>389</td>
<td>162</td>
<td>237</td>
<td>293</td>
<td>147</td>
<td>177</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mean</td>
<td>6.346026e+17</td>
<td>NaN</td>
<td>NaN</td>
<td>2011.423022</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">std</td>
<td>2.515071e+14</td>
<td>NaN</td>
<td>NaN</td>
<td>0.905977</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">min</td>
<td>6.341330e+17</td>
<td>NaN</td>
<td>NaN</td>
<td>2009.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">25%</td>
<td>6.343954e+17</td>
<td>NaN</td>
<td>NaN</td>
<td>2011.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">50%</td>
<td>6.345835e+17</td>
<td>NaN</td>
<td>NaN</td>
<td>2011.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">75%</td>
<td>6.348005e+17</td>
<td>NaN</td>
<td>NaN</td>
<td>2012.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">max</td>
<td>6.350730e+17</td>
<td>NaN</td>
<td>NaN</td>
<td>2013.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

<p>11 rows × 72 columns</p>
</div>
</div>
</div>
<p>Some text columns appear to have values that only contain a single hyphen (-); these will have to be investigated later.</p>
</section>
</section>
<section id="dete-survey" class="level2">
<h2 class="anchored" data-anchor-id="dete-survey">DETE Survey</h2>
<p>The DETE employee exit survey can be found <a href="https://data.gov.au/dataset/ds-qld-fe96ff30-d157-4a81-851d-215f2a0fe26d/details?q=exit%20survey">here</a>. The copy used in this project is a slightly modified version downloaded from Dataquest for convenience. It is still complete in terms of the number of entries.</p>
<section id="columns-1" class="level3">
<h3 class="anchored" data-anchor-id="columns-1">Columns</h3>
<p>Below are the column names and types.</p>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>dete <span class="op">=</span> pd.read_csv(<span class="st">"./private/2021-06-01-EES-Files/dete_survey.csv"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>dete.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 822 entries, 0 to 821
Data columns (total 56 columns):
 #   Column                               Non-Null Count  Dtype 
---  ------                               --------------  ----- 
 0   ID                                   822 non-null    int64 
 1   SeparationType                       822 non-null    object
 2   Cease Date                           822 non-null    object
 3   DETE Start Date                      822 non-null    object
 4   Role Start Date                      822 non-null    object
 5   Position                             817 non-null    object
 6   Classification                       455 non-null    object
 7   Region                               822 non-null    object
 8   Business Unit                        126 non-null    object
 9   Employment Status                    817 non-null    object
 10  Career move to public sector         822 non-null    bool  
 11  Career move to private sector        822 non-null    bool  
 12  Interpersonal conflicts              822 non-null    bool  
 13  Job dissatisfaction                  822 non-null    bool  
 14  Dissatisfaction with the department  822 non-null    bool  
 15  Physical work environment            822 non-null    bool  
 16  Lack of recognition                  822 non-null    bool  
 17  Lack of job security                 822 non-null    bool  
 18  Work location                        822 non-null    bool  
 19  Employment conditions                822 non-null    bool  
 20  Maternity/family                     822 non-null    bool  
 21  Relocation                           822 non-null    bool  
 22  Study/Travel                         822 non-null    bool  
 23  Ill Health                           822 non-null    bool  
 24  Traumatic incident                   822 non-null    bool  
 25  Work life balance                    822 non-null    bool  
 26  Workload                             822 non-null    bool  
 27  None of the above                    822 non-null    bool  
 28  Professional Development             808 non-null    object
 29  Opportunities for promotion          735 non-null    object
 30  Staff morale                         816 non-null    object
 31  Workplace issue                      788 non-null    object
 32  Physical environment                 817 non-null    object
 33  Worklife balance                     815 non-null    object
 34  Stress and pressure support          810 non-null    object
 35  Performance of supervisor            813 non-null    object
 36  Peer support                         812 non-null    object
 37  Initiative                           813 non-null    object
 38  Skills                               811 non-null    object
 39  Coach                                767 non-null    object
 40  Career Aspirations                   746 non-null    object
 41  Feedback                             792 non-null    object
 42  Further PD                           768 non-null    object
 43  Communication                        814 non-null    object
 44  My say                               812 non-null    object
 45  Information                          816 non-null    object
 46  Kept informed                        813 non-null    object
 47  Wellness programs                    766 non-null    object
 48  Health &amp; Safety                      793 non-null    object
 49  Gender                               798 non-null    object
 50  Age                                  811 non-null    object
 51  Aboriginal                           16 non-null     object
 52  Torres Strait                        3 non-null      object
 53  South Sea                            7 non-null      object
 54  Disability                           23 non-null     object
 55  NESB                                 32 non-null     object
dtypes: bool(18), int64(1), object(37)
memory usage: 258.6+ KB</code></pre>
</div>
</div>
<p><code>ID</code> contains integers, whereas all other columns either contain text or booleans. Also, many of the columns have missing values.</p>
<p>There are 822 rows (employees) and 56 columns (survey questions). Dataquest describes a few notable columns as follows:</p>
<ul>
<li>“<code>ID</code>: An id used to identify the participant of the survey”</li>
<li>“<code>SeparationType</code>: The reason why the person’s employment ended”</li>
<li>“<code>Cease Date</code>: The year or month the person’s employment ended”</li>
<li>“<code>DETE Start Date</code>: The year the person began employment with the DETE”</li>
</ul>
<p>Also, if we look closely, we can see that many of the columns in the DETE dataset match columns in the TAFE dataset. For example:</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"TAFE Columns"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">list</span>(tafe.columns[<span class="dv">5</span>:<span class="dv">17</span>]))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">DETE Columns"</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">list</span>(dete.columns[<span class="dv">10</span>:<span class="dv">28</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>TAFE Columns
['Contributing Factors. Career Move - Public Sector ', 'Contributing Factors. Career Move - Private Sector ', 'Contributing Factors. Career Move - Self-employment', 'Contributing Factors. Ill Health', 'Contributing Factors. Maternity/Family', 'Contributing Factors. Dissatisfaction', 'Contributing Factors. Job Dissatisfaction', 'Contributing Factors. Interpersonal Conflict', 'Contributing Factors. Study', 'Contributing Factors. Travel', 'Contributing Factors. Other', 'Contributing Factors. NONE']

DETE Columns
['Career move to public sector', 'Career move to private sector', 'Interpersonal conflicts', 'Job dissatisfaction', 'Dissatisfaction with the department', 'Physical work environment', 'Lack of recognition', 'Lack of job security', 'Work location', 'Employment conditions', 'Maternity/family', 'Relocation', 'Study/Travel', 'Ill Health', 'Traumatic incident', 'Work life balance', 'Workload', 'None of the above']</code></pre>
</div>
</div>
<p>These two sets of columns represent the “Contributing Factors” group in each survey. These are some of the columns that we want to keep for analysis; this will be addressed in data cleaning later.</p>
</section>
<section id="descriptive-statistics-1" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-statistics-1">Descriptive Statistics</h3>
<p>We can view descriptive statistics for all columns below.</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>dete.describe(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    include <span class="op">=</span> <span class="st">"all"</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    datetime_is_numeric <span class="op">=</span> <span class="va">True</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ID</th>
<th data-quarto-table-cell-role="th">SeparationType</th>
<th data-quarto-table-cell-role="th">Cease Date</th>
<th data-quarto-table-cell-role="th">DETE Start Date</th>
<th data-quarto-table-cell-role="th">Role Start Date</th>
<th data-quarto-table-cell-role="th">Position</th>
<th data-quarto-table-cell-role="th">Classification</th>
<th data-quarto-table-cell-role="th">Region</th>
<th data-quarto-table-cell-role="th">Business Unit</th>
<th data-quarto-table-cell-role="th">Employment Status</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">Kept informed</th>
<th data-quarto-table-cell-role="th">Wellness programs</th>
<th data-quarto-table-cell-role="th">Health &amp; Safety</th>
<th data-quarto-table-cell-role="th">Gender</th>
<th data-quarto-table-cell-role="th">Age</th>
<th data-quarto-table-cell-role="th">Aboriginal</th>
<th data-quarto-table-cell-role="th">Torres Strait</th>
<th data-quarto-table-cell-role="th">South Sea</th>
<th data-quarto-table-cell-role="th">Disability</th>
<th data-quarto-table-cell-role="th">NESB</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>822.000000</td>
<td>822</td>
<td>822</td>
<td>822</td>
<td>822</td>
<td>817</td>
<td>455</td>
<td>822</td>
<td>126</td>
<td>817</td>
<td>...</td>
<td>813</td>
<td>766</td>
<td>793</td>
<td>798</td>
<td>811</td>
<td>16</td>
<td>3</td>
<td>7</td>
<td>23</td>
<td>32</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">unique</td>
<td>NaN</td>
<td>9</td>
<td>25</td>
<td>51</td>
<td>46</td>
<td>15</td>
<td>8</td>
<td>9</td>
<td>14</td>
<td>5</td>
<td>...</td>
<td>6</td>
<td>6</td>
<td>6</td>
<td>2</td>
<td>10</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">top</td>
<td>NaN</td>
<td>Age Retirement</td>
<td>2012</td>
<td>Not Stated</td>
<td>Not Stated</td>
<td>Teacher</td>
<td>Primary</td>
<td>Metropolitan</td>
<td>Education Queensland</td>
<td>Permanent Full-time</td>
<td>...</td>
<td>A</td>
<td>A</td>
<td>A</td>
<td>Female</td>
<td>61 or older</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">freq</td>
<td>NaN</td>
<td>285</td>
<td>344</td>
<td>73</td>
<td>98</td>
<td>324</td>
<td>161</td>
<td>135</td>
<td>54</td>
<td>434</td>
<td>...</td>
<td>401</td>
<td>253</td>
<td>386</td>
<td>573</td>
<td>222</td>
<td>16</td>
<td>3</td>
<td>7</td>
<td>23</td>
<td>32</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mean</td>
<td>411.693431</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">std</td>
<td>237.705820</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">min</td>
<td>1.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">25%</td>
<td>206.250000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">50%</td>
<td>411.500000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">75%</td>
<td>616.750000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">max</td>
<td>823.000000</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

<p>11 rows × 56 columns</p>
</div>
</div>
</div>
<p>The <code>Cease Date</code>, <code>DETE Start Date</code>, and <code>Role Start Date</code> columns are interesting because these are in text format and some of the values are <code>"Not Stated"</code>.</p>
<p>Also, based on counts of non-null values shown earlier, some columns have many missing values. These will have to be addressed in data cleaning.</p>
</section>
</section>
</section>
<section id="data-cleaning" class="level1">
<h1>Data Cleaning</h1>
<section id="placeholders-for-missing-values" class="level2">
<h2 class="anchored" data-anchor-id="placeholders-for-missing-values">Placeholders for Missing Values</h2>
<p>Earlier, we noticed that some columns in the DETE data contain “Not Stated” values. These are likely to be placeholders for missing data.</p>
<p>Therefore, we can replace all “Not Stated” values with <code>np.nan</code> null values.</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>dete <span class="op">=</span> dete.replace(<span class="st">"Not Stated"</span>, np.nan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="dropping-columns" class="level2">
<h2 class="anchored" data-anchor-id="dropping-columns">Dropping Columns</h2>
<p>In the TAFE dataset, there are 4 other big groups of columns other than Contributing Factors:</p>
<ul>
<li>Institute Views</li>
<li>Work Unit Views</li>
<li>Induction Info</li>
<li>Workplace</li>
</ul>
<p>We want to remove these columns in order to limit the columns in our dataset to the most relevant ones. This is done below.</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>tafe <span class="op">=</span> tafe.drop(</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    labels <span class="op">=</span> tafe.columns[<span class="dv">17</span>:<span class="dv">66</span>],</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    axis <span class="op">=</span> <span class="dv">1</span>,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="bu">list</span>(tafe.columns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>['Record ID',
 'Institute',
 'WorkArea',
 'CESSATION YEAR',
 'Reason for ceasing employment',
 'Contributing Factors. Career Move - Public Sector ',
 'Contributing Factors. Career Move - Private Sector ',
 'Contributing Factors. Career Move - Self-employment',
 'Contributing Factors. Ill Health',
 'Contributing Factors. Maternity/Family',
 'Contributing Factors. Dissatisfaction',
 'Contributing Factors. Job Dissatisfaction',
 'Contributing Factors. Interpersonal Conflict',
 'Contributing Factors. Study',
 'Contributing Factors. Travel',
 'Contributing Factors. Other',
 'Contributing Factors. NONE',
 'Gender. What is your Gender?',
 'CurrentAge. Current Age',
 'Employment Type. Employment Type',
 'Classification. Classification',
 'LengthofServiceOverall. Overall Length of Service at Institute (in years)',
 'LengthofServiceCurrent. Length of Service at current workplace (in years)']</code></pre>
</div>
</div>
<p>There are now only 23 columns in the TAFE dataset.</p>
<p>Earlier, in the Data Overview, we mentioned that DETE has similar columns to the ones in TAFE. For example, look at the columns from indices 28 to 48:</p>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>dete.columns[<span class="dv">28</span>:<span class="dv">49</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>Index(['Professional Development', 'Opportunities for promotion',
       'Staff morale', 'Workplace issue', 'Physical environment',
       'Worklife balance', 'Stress and pressure support',
       'Performance of supervisor', 'Peer support', 'Initiative', 'Skills',
       'Coach', 'Career Aspirations', 'Feedback', 'Further PD',
       'Communication', 'My say', 'Information', 'Kept informed',
       'Wellness programs', 'Health &amp; Safety'],
      dtype='object')</code></pre>
</div>
</div>
<p>These are equivalent to the TAFE columns under the Institute Views, Work Unit Views, Induction Info, and Workspace groups. We don’t need these groups since the Contributing Factors group is directly related to the reason why the employees resigned.</p>
<p>Thus, we will remove the columns shown above from the DETE dataset.</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>dete <span class="op">=</span> dete.drop(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    dete.columns[<span class="dv">28</span>:<span class="dv">49</span>],</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    axis <span class="op">=</span> <span class="dv">1</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="bu">len</span>(dete.columns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>35</code></pre>
</div>
</div>
</section>
<section id="matching-columns-in-tafe-and-dete" class="level2">
<h2 class="anchored" data-anchor-id="matching-columns-in-tafe-and-dete">Matching Columns in TAFE and DETE</h2>
<p>Below are some important columns in TAFE and DETE which have matching information.</p>
<table class="table">
<colgroup>
<col style="width: 18%">
<col style="width: 81%">
</colgroup>
<thead>
<tr class="header">
<th>DETE Survey</th>
<th>TAFE Survey</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ID</td>
<td>Record ID</td>
</tr>
<tr class="even">
<td>SeparationType</td>
<td>Reason for ceasing employment</td>
</tr>
<tr class="odd">
<td>Cease Date</td>
<td>CESSATION YEAR</td>
</tr>
<tr class="even">
<td>DETE Start Date</td>
<td>LengthofServiceOverall. Overall Length of Service at Institute (in years)</td>
</tr>
<tr class="odd">
<td>Age</td>
<td>CurrentAge. Current Age</td>
</tr>
<tr class="even">
<td>Gender</td>
<td>Gender. What is your Gender?</td>
</tr>
</tbody>
</table>
<p>Notably, <code>DETE Start Date</code> and <code>LengthofServiceOverall</code> are matching columns because one can tell how long the employee has been working based on the date when they first started working.</p>
<p>We want to make the column names the same between the two datasets.</p>
<p>Before we do that, we will simplify the names in DETE.</p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>dete.columns <span class="op">=</span> (</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    dete.columns</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">str</span>.lower() <span class="co"># All lowercase</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">str</span>.strip() <span class="co"># Remove whitespace on sides</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">str</span>.replace(<span class="st">" "</span>, <span class="st">"_"</span>) <span class="co"># Replace spaces with underscores</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>dete.columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>Index(['id', 'separationtype', 'cease_date', 'dete_start_date',
       'role_start_date', 'position', 'classification', 'region',
       'business_unit', 'employment_status', 'career_move_to_public_sector',
       'career_move_to_private_sector', 'interpersonal_conflicts',
       'job_dissatisfaction', 'dissatisfaction_with_the_department',
       'physical_work_environment', 'lack_of_recognition',
       'lack_of_job_security', 'work_location', 'employment_conditions',
       'maternity/family', 'relocation', 'study/travel', 'ill_health',
       'traumatic_incident', 'work_life_balance', 'workload',
       'none_of_the_above', 'gender', 'age', 'aboriginal', 'torres_strait',
       'south_sea', 'disability', 'nesb'],
      dtype='object')</code></pre>
</div>
</div>
<p>The DETE columns have been simplified.</p>
<p>Next, we will change some of the TAFE column labels to match the ones in the DETE dataset.</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>new_columns <span class="op">=</span> {</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Record ID'</span>: <span class="st">'id'</span>,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'CESSATION YEAR'</span>: <span class="st">'cease_date'</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Reason for ceasing employment'</span>: <span class="st">'separationtype'</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Gender. What is your Gender?'</span>: <span class="st">'gender'</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'CurrentAge. Current Age'</span>: <span class="st">'age'</span>,</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Employment Type. Employment Type'</span>: <span class="st">'employment_status'</span>,</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Classification. Classification'</span>: <span class="st">'position'</span>,</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'LengthofServiceOverall. Overall Length of Service at Institute (in years)'</span>: <span class="st">'institute_service'</span>,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'LengthofServiceCurrent. Length of Service at current workplace (in years)'</span>: <span class="st">'role_service'</span>,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>tafe <span class="op">=</span> tafe.rename(</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>    new_columns,</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>    axis <span class="op">=</span> <span class="dv">1</span>,</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a><span class="bu">list</span>(tafe.columns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>['id',
 'Institute',
 'WorkArea',
 'cease_date',
 'separationtype',
 'Contributing Factors. Career Move - Public Sector ',
 'Contributing Factors. Career Move - Private Sector ',
 'Contributing Factors. Career Move - Self-employment',
 'Contributing Factors. Ill Health',
 'Contributing Factors. Maternity/Family',
 'Contributing Factors. Dissatisfaction',
 'Contributing Factors. Job Dissatisfaction',
 'Contributing Factors. Interpersonal Conflict',
 'Contributing Factors. Study',
 'Contributing Factors. Travel',
 'Contributing Factors. Other',
 'Contributing Factors. NONE',
 'gender',
 'age',
 'employment_status',
 'position',
 'institute_service',
 'role_service']</code></pre>
</div>
</div>
<p>The Contributing Factors columns’ names haven’t been changed yet, but this will be dealt with later.</p>
</section>
<section id="identifying-employees-who-resigned" class="level2">
<h2 class="anchored" data-anchor-id="identifying-employees-who-resigned">Identifying Employees who Resigned</h2>
<p>The DETE and TAFE exit surveys were given to all employees who left the institutions. Some of them were terminated from employment, some resigned, and some retired.</p>
<p>The goal of this project is to find out why employees resigned. Thus, we have to find out who resigned, and drop the data for the rest.</p>
<p>Let’s do this for the DETE dataset first. The <code>separationtype</code> column explains the reason why the employee ceased to work at the institution. What values does this column contain?</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>dete[<span class="st">"separationtype"</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>Age Retirement                          285
Resignation-Other reasons               150
Resignation-Other employer               91
Resignation-Move overseas/interstate     70
Voluntary Early Retirement (VER)         67
Ill Health Retirement                    61
Other                                    49
Contract Expired                         34
Termination                              15
Name: separationtype, dtype: int64</code></pre>
</div>
</div>
<p>It looks like the values that are relevant to us are the ones that start with “Resignation.” We’ll keep the rows which indicate resignation and drop the rest.</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>dete <span class="op">=</span> dete.loc[</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Check if the string starts with "Resignation."</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    dete[<span class="st">"separationtype"</span>].<span class="bu">str</span>.startswith(<span class="st">"Resignation"</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>dete.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>(311, 35)</code></pre>
</div>
</div>
<p>After we dropped non-resignation rows, the DETE dataset was left with 311 rows.</p>
<p>Next, we’ll do the same for the TAFE dataset. What are the values in its <code>separationtype</code> column?</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>tafe[<span class="st">"separationtype"</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>Resignation                 340
Contract Expired            127
Retrenchment/ Redundancy    104
Retirement                   82
Transfer                     25
Termination                  23
Name: separationtype, dtype: int64</code></pre>
</div>
</div>
<p>This time, there is only one value which indicates resignation. We’ll use that to identify the rows to keep.</p>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>tafe <span class="op">=</span> tafe.loc[</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Check if the value is "Resignation."</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    tafe[<span class="st">"separationtype"</span>] <span class="op">==</span> <span class="st">"Resignation"</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>tafe.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>(340, 23)</code></pre>
</div>
</div>
<p>Dropping rows resulted in having 340 rows left in the TAFE dataset.</p>
<p>Now, both datasets have been narrowed down to data about employees who intentionally left the institutions.</p>
</section>
<section id="date-columns" class="level2">
<h2 class="anchored" data-anchor-id="date-columns">Date Columns</h2>
<p>Next, we’ll clean and inspect date columns. Specifically, these are:</p>
<ul>
<li>DETE dataset
<ul>
<li><code>dete_start_date</code>: The date when the employee started to work at DETE.</li>
<li><code>cease_date</code>: The date when the employee ceased to work at DETE.</li>
</ul></li>
<li>TAFE dataset
<ul>
<li><code>cease_date</code>: The date when the employee ceased to work at TAFE.</li>
</ul></li>
</ul>
<p>Let’s start with DETE’s <code>cease_date</code>. What are its values?</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>dete[<span class="st">"cease_date"</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<pre><code>2012       126
2013        74
01/2014     22
12/2013     17
06/2013     14
09/2013     11
07/2013      9
11/2013      9
10/2013      6
08/2013      4
05/2012      2
05/2013      2
07/2012      1
2010         1
09/2010      1
07/2006      1
Name: cease_date, dtype: int64</code></pre>
</div>
</div>
<p>We can see that some values only contain years, and others state a month before the year. Since we can’t assume the month for entries without one, we will remove all of the months. Only the years will remain, and we will store them as numerical data.</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>dete[<span class="st">"cease_date"</span>] <span class="op">=</span> (</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>    dete[<span class="st">"cease_date"</span>]</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">str</span>.extract(<span class="st">"(20[0-1][0-9])"</span>) <span class="co"># Extract year using a regular expression</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    .astype(np.float64) <span class="co"># Turn years into decimals</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>dete[<span class="st">"cease_date"</span>].value_counts().sort_index()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>2006.0      1
2010.0      2
2012.0    129
2013.0    146
2014.0     22
Name: cease_date, dtype: int64</code></pre>
</div>
</div>
<p>The DETE <code>cease_date</code> column now only contains year values. These range from 2006 to 2014.</p>
<p>Next, let’s look at DETE’s <code>dete_start_date</code> column.</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>dete[<span class="st">"dete_start_date"</span>].value_counts().sort_index()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<pre><code>1963     1
1971     1
1972     1
1973     1
1974     2
1975     1
1976     2
1977     1
1980     5
1982     1
1983     2
1984     1
1985     3
1986     3
1987     1
1988     4
1989     4
1990     5
1991     4
1992     6
1993     5
1994     6
1995     4
1996     6
1997     5
1998     6
1999     8
2000     9
2001     3
2002     6
2003     6
2004    14
2005    15
2006    13
2007    21
2008    22
2009    13
2010    17
2011    24
2012    21
2013    10
Name: dete_start_date, dtype: int64</code></pre>
</div>
</div>
<p>The column contains only years, no months, so it is quite clean. Most of the values are from 2004 to 2013. The years in the late 1900’s don’t seem like outliers because there are many values spread throughout those years.</p>
<p>It also makes sense that there are no <code>dete_start_date</code> values after 2014, since the latest <code>cease_date</code> is 2014.</p>
<p>There’s no need to clean this column, but let’s convert it to numerical data for consistency.</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>dete[<span class="st">"dete_start_date"</span>] <span class="op">=</span> dete[<span class="st">"dete_start_date"</span>].astype(np.float64)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Lastly, let’s look at the TAFE dataset’s <code>cease_date</code> column.</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>tafe[<span class="st">"cease_date"</span>].value_counts().sort_index()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>2009.0      2
2010.0     68
2011.0    116
2012.0     94
2013.0     55
Name: cease_date, dtype: int64</code></pre>
</div>
</div>
<p>The data here looks like it’s already clean. The years are expressed as decimals, and there are no outliers to clean up. This column won’t be changed.</p>
<p>The TAFE <code>cease_date</code> years range from 2009 to 2013. DETE’s <code>cease_date</code> values range from 2006 to 2014. Therefore, both datasets give information about roughly the same period in time.</p>
</section>
<section id="years-of-service" class="level2">
<h2 class="anchored" data-anchor-id="years-of-service">Years of Service</h2>
<p>Remember that one of the goals of the project is to compare dissatisfaction rates between resignees who had worked for a <strong>short time</strong> and those who had worked for a <strong>longer time</strong>. Thus, we need to know how many years of service each employee has had.</p>
<p>The TAFE dataset already has a column called <code>institute_service</code> which gives information on this.</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>tafe[<span class="st">"institute_service"</span>].value_counts().sort_index()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>1-2                   64
11-20                 26
3-4                   63
5-6                   33
7-10                  21
Less than 1 year      73
More than 20 years    10
Name: institute_service, dtype: int64</code></pre>
</div>
</div>
<p>These values are somewhat difficult to use since these indicate <strong>ranges</strong> of years of service. This will be dealt with later, but for now, we have to make a matching column in the DETE dataset.</p>
<p>In order to do this, we will subtract <code>dete_start_date</code> from <code>cease_date</code>. This will result in the number of years that each employee has spent working at DETE. The new column will be called <code>institute_service</code> like in the TAFE dataset.</p>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>dete[<span class="st">"institute_service"</span>] <span class="op">=</span> dete[<span class="st">"cease_date"</span>] <span class="op">-</span> dete[<span class="st">"dete_start_date"</span>]</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>dete[<span class="st">"institute_service"</span>].value_counts(bins <span class="op">=</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<pre><code>(-0.05, 4.9]    92
(4.9, 9.8]      75
(9.8, 14.7]     30
(14.7, 19.6]    26
(19.6, 24.5]    24
(24.5, 29.4]     8
(29.4, 34.3]     8
(34.3, 39.2]     7
(39.2, 44.1]     2
(44.1, 49.0]     1
Name: institute_service, dtype: int64</code></pre>
</div>
</div>
<p>It can be seen that DETE employees’ years of service range from under 4.9 to over 44.1. Let’s view the distribution in a histogram.</p>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>sns.histplot(</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> dete,</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> <span class="st">"institute_service"</span>,</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"DETE Employees' Years of Service"</span>)</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Years of Service"</span>)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2021-06-01-Employee-Exit-Survey-Data-Cleaning-Aggregation_files/figure-html/cell-25-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The distribution is right-skewed. Most employees who resigned had worked at DETE for under 10 years.</p>
</section>
<section id="contributing-factors-columns" class="level2">
<h2 class="anchored" data-anchor-id="contributing-factors-columns">“Contributing Factors” Columns</h2>
<p>The Contributing Factors columns are about factors which may have influenced the employee’s choice to resign. In the TAFE dataset, these columns have hyphen (<code>"-"</code>) values. This leads us to wonder what they represent, and whether or not we have to clean them.</p>
<p>Let’s look at column 5, one of the columns with hyphens.</p>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>tafe.iloc[:, <span class="dv">5</span>].value_counts(dropna <span class="op">=</span> <span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>-                              284
Career Move - Public Sector     48
NaN                              8
Name: Contributing Factors. Career Move - Public Sector , dtype: int64</code></pre>
</div>
</div>
<p>Most of the values are hyphens. The rest are null values or <code>"Career Move - Public Sector"</code>.</p>
<p>We can infer that the Contributing Factors group of columns represent <strong>options in a checkbox item</strong> in the survey. That’s why each column only has 2 valid values:</p>
<ul>
<li><code>"-"</code> means that the option was <strong>not selected</strong>.</li>
<li><code>"Career Move - Public Sector"</code> means that the option was <strong>selected</strong>.</li>
</ul>
<p>Thus, we can change the values in column 5 into <code>True</code> (selected) and <code>False</code> (not selected) for ease of use.</p>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a function to be applied to the column.</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> identify_selection(value):</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> pd.isnull(value):</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> np.nan</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> value <span class="op">!=</span> <span class="st">"-"</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply the function elementwise.</span></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>tafe.iloc[:, <span class="dv">5</span>] <span class="op">=</span> tafe.iloc[:, <span class="dv">5</span>].<span class="bu">apply</span>(identify_selection)</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>tafe.iloc[:, <span class="dv">5</span>].value_counts(dropna <span class="op">=</span> <span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>False    284
True      48
NaN        8
Name: Contributing Factors. Career Move - Public Sector , dtype: int64</code></pre>
</div>
</div>
<p>Now, the column only has <code>True</code>, <code>False</code>, and <code>NaN</code> values.</p>
<p>Let us apply this transformaton to the entire group of “Contributing Factors” columns (5 to 16).</p>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>tafe.iloc[:, <span class="dv">6</span>:<span class="dv">17</span>] <span class="op">=</span> tafe.iloc[:, <span class="dv">6</span>:<span class="dv">17</span>].applymap(identify_selection)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>tafe.iloc[:, <span class="dv">5</span>:<span class="dv">17</span>].head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="27">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Contributing Factors. Career Move - Public Sector</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Career Move - Private Sector</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Career Move - Self-employment</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Ill Health</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Maternity/Family</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Dissatisfaction</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Job Dissatisfaction</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Interpersonal Conflict</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Study</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Travel</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Other</th>
<th data-quarto-table-cell-role="th">Contributing Factors. NONE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">6</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">7</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>False</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Since these columns are now boolean columns, these will be easier to use in analysis.</p>
<p>It is worth noting that what we did matches the format used for Contributing Factors columns in DETE:</p>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>dete.iloc[:<span class="dv">5</span>, <span class="dv">10</span>:<span class="dv">28</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="28">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">career_move_to_public_sector</th>
<th data-quarto-table-cell-role="th">career_move_to_private_sector</th>
<th data-quarto-table-cell-role="th">interpersonal_conflicts</th>
<th data-quarto-table-cell-role="th">job_dissatisfaction</th>
<th data-quarto-table-cell-role="th">dissatisfaction_with_the_department</th>
<th data-quarto-table-cell-role="th">physical_work_environment</th>
<th data-quarto-table-cell-role="th">lack_of_recognition</th>
<th data-quarto-table-cell-role="th">lack_of_job_security</th>
<th data-quarto-table-cell-role="th">work_location</th>
<th data-quarto-table-cell-role="th">employment_conditions</th>
<th data-quarto-table-cell-role="th">maternity/family</th>
<th data-quarto-table-cell-role="th">relocation</th>
<th data-quarto-table-cell-role="th">study/travel</th>
<th data-quarto-table-cell-role="th">ill_health</th>
<th data-quarto-table-cell-role="th">traumatic_incident</th>
<th data-quarto-table-cell-role="th">work_life_balance</th>
<th data-quarto-table-cell-role="th">workload</th>
<th data-quarto-table-cell-role="th">none_of_the_above</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>False</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>True</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">11</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>True</td>
<td>True</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Thus, we will be able to use similar techniques to identify dissatisfaction in both datasets.</p>
</section>
<section id="identifying-dissatisfaction" class="level2">
<h2 class="anchored" data-anchor-id="identifying-dissatisfaction">Identifying Dissatisfaction</h2>
<p>This project focuses on employees who resigned due to <strong>dissatisfaction with their work</strong> at the government institute. Thus, we have to identify which employees were dissatisfied.</p>
<p>In the TAFE dataset, the following columns indicate dissatisfaction:</p>
<ul>
<li><code>Contributing Factors. Dissatisfaction</code></li>
<li><code>Contributing Factors. Job Dissatisfaction</code></li>
</ul>
<p>We will create a new <code>dissatisfaction</code> column. It will be a boolean column that contains <code>True</code> if at least 1 of the above columns has a value of <code>True</code>.</p>
<div class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>tafe[<span class="st">"dissatisfaction"</span>] <span class="op">=</span> (</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>    tafe[[</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Contributing Factors. Dissatisfaction"</span>,</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Contributing Factors. Job Dissatisfaction"</span>,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>    ]]</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">any</span>(axis <span class="op">=</span> <span class="dv">1</span>, skipna <span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>tafe[<span class="st">"dissatisfaction"</span>].value_counts(dropna <span class="op">=</span> <span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="29">
<pre><code>False    241
True      99
Name: dissatisfaction, dtype: int64</code></pre>
</div>
</div>
<p>It looks like 91 employees in the TAFE dataset resigned due to dissatisfaction.</p>
<p>As for the DETE dataset, there are many relevant columns.</p>
<ul>
<li><code>job_dissatisfaction</code></li>
<li><code>dissatisfaction_with_the_department</code></li>
<li><code>physical_work_environment</code></li>
<li><code>lack_of_recognition</code></li>
<li><code>lack_of_job_security</code></li>
<li><code>work_location</code></li>
<li><code>employment_conditions</code></li>
<li><code>work_life_balance</code></li>
<li><code>workload</code></li>
</ul>
<p>Remember that in the survey, these phrases were options in a checkbox item asking why the employee left. A <code>True</code> value in any of these columns means that the employee considered it a reason why he/she resigned.</p>
<p>We will create a new <code>dissatisfaction</code> column in the DETE dataset in the same way as we did for the TAFE dataset. If at least 1 of the above columns is <code>True</code>, the corresponding value in the new column will be <code>True</code>.</p>
<div class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>dete[<span class="st">"dissatisfaction"</span>] <span class="op">=</span> (</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>    dete[[</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>        <span class="st">'job_dissatisfaction'</span>,</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>        <span class="st">'dissatisfaction_with_the_department'</span>,</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">'physical_work_environment'</span>, <span class="st">'lack_of_recognition'</span>,</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">'lack_of_job_security'</span>,</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">'work_location'</span>,</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">'employment_conditions'</span>,</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">'work_life_balance'</span>, </span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">'workload'</span>,</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>    ]]</span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">any</span>(axis <span class="op">=</span> <span class="dv">1</span>, skipna <span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>dete[<span class="st">"dissatisfaction"</span>].value_counts(dropna <span class="op">=</span> <span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<pre><code>False    162
True     149
Name: dissatisfaction, dtype: int64</code></pre>
</div>
</div>
<p>The results show that 149 of DETE employees who resigned had been dissatisfied.</p>
</section>
<section id="combining-dete-and-tafe" class="level2">
<h2 class="anchored" data-anchor-id="combining-dete-and-tafe">Combining DETE and TAFE</h2>
<p>At this point, the data cleaning we’ve done is sufficient for us to combine the two datasets. We will stack them vertically; they will share columns with identical names.</p>
<p>We will still need to be able to differentiate between DETE and TAFE employees, so we will indicate this in a new column.</p>
<p>In the DETE dataset, the new <code>institute</code> column will contain the string <code>"DETE"</code>.</p>
<div class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>dete[<span class="st">"institute"</span>] <span class="op">=</span> <span class="st">"DETE"</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>dete[<span class="st">"institute"</span>].head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<pre><code>3     DETE
5     DETE
8     DETE
9     DETE
11    DETE
Name: institute, dtype: object</code></pre>
</div>
</div>
<p>The value in the TAFE dataset will be <code>"TAFE"</code>.</p>
<div class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>tafe[<span class="st">"institute"</span>] <span class="op">=</span> <span class="st">"TAFE"</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>tafe[<span class="st">"institute"</span>].head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="32">
<pre><code>3    TAFE
4    TAFE
5    TAFE
6    TAFE
7    TAFE
Name: institute, dtype: object</code></pre>
</div>
</div>
<p>Let’s now concatenate the 2 datasets vertically.</p>
<div class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>combined <span class="op">=</span> pd.concat(</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>    [dete, tafe],</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>    axis <span class="op">=</span> <span class="dv">0</span>, <span class="co"># Vertical concatenation</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>    ignore_index <span class="op">=</span> <span class="va">True</span>,</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(combined.shape)</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>combined.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(651, 53)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="33">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">id</th>
<th data-quarto-table-cell-role="th">separationtype</th>
<th data-quarto-table-cell-role="th">cease_date</th>
<th data-quarto-table-cell-role="th">dete_start_date</th>
<th data-quarto-table-cell-role="th">role_start_date</th>
<th data-quarto-table-cell-role="th">position</th>
<th data-quarto-table-cell-role="th">classification</th>
<th data-quarto-table-cell-role="th">region</th>
<th data-quarto-table-cell-role="th">business_unit</th>
<th data-quarto-table-cell-role="th">employment_status</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Ill Health</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Maternity/Family</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Dissatisfaction</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Job Dissatisfaction</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Interpersonal Conflict</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Study</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Travel</th>
<th data-quarto-table-cell-role="th">Contributing Factors. Other</th>
<th data-quarto-table-cell-role="th">Contributing Factors. NONE</th>
<th data-quarto-table-cell-role="th">role_service</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>4.0</td>
<td>Resignation-Other reasons</td>
<td>2012.0</td>
<td>2005.0</td>
<td>2006</td>
<td>Teacher</td>
<td>Primary</td>
<td>Central Queensland</td>
<td>NaN</td>
<td>Permanent Full-time</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>6.0</td>
<td>Resignation-Other reasons</td>
<td>2012.0</td>
<td>1994.0</td>
<td>1997</td>
<td>Guidance Officer</td>
<td>NaN</td>
<td>Central Office</td>
<td>Education Queensland</td>
<td>Permanent Full-time</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>9.0</td>
<td>Resignation-Other reasons</td>
<td>2012.0</td>
<td>2009.0</td>
<td>2009</td>
<td>Teacher</td>
<td>Secondary</td>
<td>North Queensland</td>
<td>NaN</td>
<td>Permanent Full-time</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>10.0</td>
<td>Resignation-Other employer</td>
<td>2012.0</td>
<td>1997.0</td>
<td>2008</td>
<td>Teacher Aide</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>Permanent Part-time</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>12.0</td>
<td>Resignation-Move overseas/interstate</td>
<td>2012.0</td>
<td>2009.0</td>
<td>2009</td>
<td>Teacher</td>
<td>Secondary</td>
<td>Far North Queensland</td>
<td>NaN</td>
<td>Permanent Full-time</td>
<td>...</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

<p>5 rows × 53 columns</p>
</div>
</div>
</div>
<p>The combined dataset has 651 rows (employees) and 53 columns.</p>
<p>Given our research questions, the most important columns to keep are <code>institute_service</code>, <code>age</code>, and <code>dissatisfaction</code>. We would only keep the other columns if we wanted to group the employees on certain characteristics.</p>
<p>Thus, we will remove columns that have under 500 non-null values. These columns wouldn’t have enough useful information for us to use.</p>
<div class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>combined.dropna(</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>    axis <span class="op">=</span> <span class="dv">1</span>,</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>    thresh <span class="op">=</span> <span class="dv">500</span>,</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>    inplace <span class="op">=</span> <span class="va">True</span>,</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(combined.shape)</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>combined.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(651, 10)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="34">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">id</th>
<th data-quarto-table-cell-role="th">separationtype</th>
<th data-quarto-table-cell-role="th">cease_date</th>
<th data-quarto-table-cell-role="th">position</th>
<th data-quarto-table-cell-role="th">employment_status</th>
<th data-quarto-table-cell-role="th">gender</th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">institute_service</th>
<th data-quarto-table-cell-role="th">dissatisfaction</th>
<th data-quarto-table-cell-role="th">institute</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>4.0</td>
<td>Resignation-Other reasons</td>
<td>2012.0</td>
<td>Teacher</td>
<td>Permanent Full-time</td>
<td>Female</td>
<td>36-40</td>
<td>7.0</td>
<td>False</td>
<td>DETE</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>6.0</td>
<td>Resignation-Other reasons</td>
<td>2012.0</td>
<td>Guidance Officer</td>
<td>Permanent Full-time</td>
<td>Female</td>
<td>41-45</td>
<td>18.0</td>
<td>True</td>
<td>DETE</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>9.0</td>
<td>Resignation-Other reasons</td>
<td>2012.0</td>
<td>Teacher</td>
<td>Permanent Full-time</td>
<td>Female</td>
<td>31-35</td>
<td>3.0</td>
<td>False</td>
<td>DETE</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>10.0</td>
<td>Resignation-Other employer</td>
<td>2012.0</td>
<td>Teacher Aide</td>
<td>Permanent Part-time</td>
<td>Female</td>
<td>46-50</td>
<td>15.0</td>
<td>True</td>
<td>DETE</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>12.0</td>
<td>Resignation-Move overseas/interstate</td>
<td>2012.0</td>
<td>Teacher</td>
<td>Permanent Full-time</td>
<td>Male</td>
<td>31-35</td>
<td>3.0</td>
<td>False</td>
<td>DETE</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Only 10 columns were left in the dataset. The 3 most important columns were kept, along with a few columns about useful demographic data.</p>
</section>
<section id="cleaning-age-data" class="level2">
<h2 class="anchored" data-anchor-id="cleaning-age-data">Cleaning Age Data</h2>
<p>One of the goals of this project involves the <code>age</code> data. Thus, we need to ensure that this data is clean.</p>
<p>Let us view the unique values in the column.</p>
<div class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>combined[<span class="st">"age"</span>].value_counts().sort_index()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="35">
<pre><code>20 or younger    10
21  25           33
21-25            29
26  30           32
26-30            35
31  35           32
31-35            29
36  40           32
36-40            41
41  45           45
41-45            48
46  50           39
46-50            42
51-55            71
56 or older      29
56-60            26
61 or older      23
Name: age, dtype: int64</code></pre>
</div>
</div>
<p>We can see that:</p>
<ul>
<li>All values represent a range of ages.</li>
<li>Some have hyphens, and others have spaces.</li>
<li>A few are phrases that say “or younger” or “or older.”</li>
</ul>
<p>Therefore, we will clean the data by defining the following function and applying it elementwise to the column:</p>
<div class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fix_age(text):</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> pd.isnull(text):</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>        result <span class="op">=</span> np.nan</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> <span class="st">"  "</span> <span class="kw">in</span> text:</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>        result <span class="op">=</span> text.replace(<span class="st">"  "</span>, <span class="st">"-"</span>)</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> text <span class="kw">in</span> [<span class="st">"56-60"</span>, <span class="st">"61 or older"</span>]:</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>        result <span class="op">=</span> <span class="st">"56 or older"</span></span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>        result <span class="op">=</span> text</span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> result</span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a>combined[<span class="st">"age"</span>] <span class="op">=</span> combined[<span class="st">"age"</span>].<span class="bu">apply</span>(fix_age)</span>
<span id="cb63-14"><a href="#cb63-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-15"><a href="#cb63-15" aria-hidden="true" tabindex="-1"></a>combined[<span class="st">"age"</span>].value_counts().sort_index()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="36">
<pre><code>20 or younger    10
21-25            62
26-30            67
31-35            61
36-40            73
41-45            93
46-50            81
51-55            71
56 or older      78
Name: age, dtype: int64</code></pre>
</div>
</div>
<p>Now, the values in the <code>age</code> column are consistent.</p>
</section>
<section id="categorizing-years-of-service" class="level2">
<h2 class="anchored" data-anchor-id="categorizing-years-of-service">Categorizing Years of Service</h2>
<p>Remember that DETE and TAFE differed in the format of their <code>institute_service</code> columns:</p>
<ul>
<li>DETE had decimal numbers representing the <strong>number of years</strong>.</li>
<li>TAFE had strings, each of which represented a <strong>range of years</strong>.</li>
</ul>
<p>We could take the TAFE ranges and replace them with the middle value of each range. However, this would make the data inaccurate.</p>
<p>Instead, we will transform the data to become more <strong>general</strong>. We’ll group the data into <strong>categories</strong> which represent ranges of years. This will apply to the entire <code>institute_service</code> column in the <code>combined</code> dataset.</p>
<p>The article <a href="https://www.businesswire.com/news/home/20171108006002/en/Age-Number-Engage-Employees-Career-Stage">“Age is Just a Number: Engage Employees by Career Stage, Too”</a> states that employee engagement can be better understood in the context of career stage, i.e., the number of years working at the company. Career stage influences an employee’s work attitude and virtues that they value in the workplace.</p>
<p>We can also say that career stage influences employees’ decisions to resign. The most obvious example of this is that a new employee isn’t very invested in the company and would be more likely to leave due to initial dissatisfaction.</p>
<p>The article gives the following 4 career stages:</p>
<ul>
<li>Newbie (0 to 3 years)</li>
<li>Sophomore (3 to 7 years)</li>
<li>Tenured (7 to 11 years)</li>
<li>Sage (11 or more years)</li>
</ul>
<p>We will use the above career stages as categories in the <code>institute_service</code> column. But first, we have to be prepared for what kinds of values we will have to transform.</p>
<div class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>combined[<span class="st">"institute_service"</span>].unique()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="37">
<pre><code>array([7.0, 18.0, 3.0, 15.0, 14.0, 5.0, nan, 30.0, 32.0, 39.0, 17.0, 9.0,
       6.0, 1.0, 35.0, 38.0, 36.0, 19.0, 4.0, 26.0, 10.0, 8.0, 2.0, 0.0,
       23.0, 13.0, 16.0, 12.0, 21.0, 20.0, 24.0, 33.0, 22.0, 28.0, 49.0,
       11.0, 41.0, 27.0, 42.0, 25.0, 29.0, 34.0, 31.0, '3-4', '7-10',
       '1-2', 'Less than 1 year', '11-20', '5-6', 'More than 20 years'],
      dtype=object)</code></pre>
</div>
</div>
<p>The values above include:</p>
<ul>
<li>Decimal numbers</li>
<li>A range of years (<code>"x-y"</code>)</li>
<li>A phrase describing a range of years (<code>"Less than x years"</code>)</li>
</ul>
<section id="extracting-numbers" class="level3">
<h3 class="anchored" data-anchor-id="extracting-numbers">Extracting Numbers</h3>
<p>Based on the values present, we will extract the number of years using the <strong>regular expression</strong> <code>([0-9]{1,2})</code>. This will capture the first 1 or 2 digit whole number in a string.</p>
<ul>
<li>For decimals, the part of the number before the decimal point will be extracted.</li>
<li>For ranges of years, the minimum year will be extracted.</li>
<li>For phrases, the first number to appear will be extracted.</li>
</ul>
<div class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>combined[<span class="st">"service_num"</span>] <span class="op">=</span> (</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>    combined[<span class="st">"institute_service"</span>]</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>    .astype(<span class="bu">str</span>) <span class="co"># Convert to strings.</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">str</span>.extract(<span class="st">"([0-9]{1,2})"</span>) <span class="co"># Extract 1 or 2-digit number.</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>    .astype(np.float64) <span class="co"># Convert to decimals.</span></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>combined[<span class="st">"service_num"</span>].unique()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="38">
<pre><code>array([ 7., 18.,  3., 15., 14.,  5., nan, 30., 32., 39., 17.,  9.,  6.,
        1., 35., 38., 36., 19.,  4., 26., 10.,  8.,  2.,  0., 23., 13.,
       16., 12., 21., 20., 24., 33., 22., 28., 49., 11., 41., 27., 42.,
       25., 29., 34., 31.])</code></pre>
</div>
</div>
<p>This worked for the decimals, as seen below. The initial and final values are identical.</p>
<div class="cell" data-execution_count="39">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>combined.loc[</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>    combined[<span class="st">"institute_service"</span>].astype(<span class="bu">str</span>).<span class="bu">str</span>.contains(<span class="st">"."</span>),</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"institute_service"</span>, <span class="st">"service_num"</span>]</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>].head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="39">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">institute_service</th>
<th data-quarto-table-cell-role="th">service_num</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>7.0</td>
<td>7.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>18.0</td>
<td>18.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3.0</td>
<td>3.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>15.0</td>
<td>15.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>3.0</td>
<td>3.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>We can tell that this worked for the ranges because the minimum value was extracted. For example, for <code>"3-4"</code>, the number 3 was extracted.</p>
<div class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>combined.loc[</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>    combined[<span class="st">"institute_service"</span>].astype(<span class="bu">str</span>).<span class="bu">str</span>.contains(<span class="st">"-"</span>),</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"institute_service"</span>, <span class="st">"service_num"</span>]</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>].head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="40">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">institute_service</th>
<th data-quarto-table-cell-role="th">service_num</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">312</td>
<td>3-4</td>
<td>3.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">313</td>
<td>7-10</td>
<td>7.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">314</td>
<td>3-4</td>
<td>3.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">315</td>
<td>3-4</td>
<td>3.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">316</td>
<td>3-4</td>
<td>3.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>It also worked for the phrases, as seen below. The number in the phrase was extracted.</p>
<div class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>combined.loc[</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>    combined[<span class="st">"institute_service"</span>].astype(<span class="bu">str</span>).<span class="bu">str</span>.contains(<span class="st">"than"</span>),</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"institute_service"</span>, <span class="st">"service_num"</span>]</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>].head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="41">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">institute_service</th>
<th data-quarto-table-cell-role="th">service_num</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">318</td>
<td>Less than 1 year</td>
<td>1.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">329</td>
<td>Less than 1 year</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">332</td>
<td>More than 20 years</td>
<td>20.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">333</td>
<td>Less than 1 year</td>
<td>1.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">334</td>
<td>Less than 1 year</td>
<td>1.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="mapping-numbers-to-categories" class="level3">
<h3 class="anchored" data-anchor-id="mapping-numbers-to-categories">Mapping Numbers to Categories</h3>
<p>Now that we have numbers, we can map them to the career stages mentioned earlier:</p>
<ul>
<li>Newbie (0 to 3 years)</li>
<li>Sophomore (3 to 7 years)</li>
<li>Tenured (7 to 11 years)</li>
<li>Sage (11 or more years)</li>
</ul>
<p>We’ll do this by defining a function then applying it elementwise to the column.</p>
<div class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function that returns career stage based on number of years.</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> career_stage(years):</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> pd.isnull(years):</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>        stage <span class="op">=</span> np.nan</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> years <span class="op">&lt;</span> <span class="fl">3.0</span>:</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>        stage <span class="op">=</span> <span class="st">"Newbie"</span></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> years <span class="op">&lt;</span> <span class="fl">7.0</span>:</span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>        stage <span class="op">=</span> <span class="st">"Sophomore"</span></span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> years <span class="op">&lt;</span> <span class="fl">11.0</span>:</span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>        stage <span class="op">=</span> <span class="st">"Tenured"</span></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> years <span class="op">&gt;=</span> <span class="fl">11.0</span>:</span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>        stage <span class="op">=</span> <span class="st">"Sage"</span></span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb72-14"><a href="#cb72-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> stage</span>
<span id="cb72-15"><a href="#cb72-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-16"><a href="#cb72-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply the function elementwise and make a new column.</span></span>
<span id="cb72-17"><a href="#cb72-17" aria-hidden="true" tabindex="-1"></a>combined[<span class="st">"service_cat"</span>] <span class="op">=</span> combined[<span class="st">"service_num"</span>].<span class="bu">apply</span>(career_stage)</span>
<span id="cb72-18"><a href="#cb72-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-19"><a href="#cb72-19" aria-hidden="true" tabindex="-1"></a>combined[<span class="st">"service_cat"</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="42">
<pre><code>Newbie       193
Sophomore    172
Sage         136
Tenured       62
Name: service_cat, dtype: int64</code></pre>
</div>
</div>
<p>The results show that most of the employees who resigned were Newbies.</p>
<p>Data cleaning is now complete, so we can go to data analysis.</p>
</section>
</section>
</section>
<section id="data-analysis" class="level1">
<h1>Data Analysis</h1>
<section id="dissatisfaction-by-age-group" class="level2">
<h2 class="anchored" data-anchor-id="dissatisfaction-by-age-group">Dissatisfaction by Age Group</h2>
<p>First, we can investigate the dissatisfaction rates of resignees by their age group.</p>
<div class="cell" data-execution_count="43">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop missing values in specific columns.</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> combined.dropna(subset <span class="op">=</span> [<span class="st">"dissatisfaction"</span>, <span class="st">"age"</span>]).copy()</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Cast booleans to integers.</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"dissatisfaction"</span>] <span class="op">=</span> df[<span class="st">"dissatisfaction"</span>].astype(<span class="bu">int</span>)</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>table_3 <span class="op">=</span> df.pivot_table(</span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>    values <span class="op">=</span> [<span class="st">"dissatisfaction"</span>],</span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a>    index <span class="op">=</span> [<span class="st">"age"</span>],</span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a>    aggfunc <span class="op">=</span> np.mean, <span class="co"># Mean will determine the percentage of True values. True is 1; False is 0.</span></span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a>).reset_index()</span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a>table_3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="43">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">dissatisfaction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>20 or younger</td>
<td>0.200000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>21-25</td>
<td>0.306452</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>26-30</td>
<td>0.417910</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>31-35</td>
<td>0.377049</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>36-40</td>
<td>0.342466</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>41-45</td>
<td>0.376344</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>46-50</td>
<td>0.382716</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>51-55</td>
<td>0.422535</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>56 or older</td>
<td>0.423077</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This table is visualized in the bar graph below.</p>
<div class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>sns.barplot(</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> table_3,</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> <span class="st">"age"</span>,</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> <span class="st">"dissatisfaction"</span>,</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>    estimator <span class="op">=</span> np.mean,</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>    ci <span class="op">=</span> <span class="va">None</span>,</span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Dissatisfaction Rates of Resignees by Age Group"</span>)</span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Age Group"</span>)</span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Percentage of Resignees who were Dissatisfied"</span>)</span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation <span class="op">=</span> <span class="dv">30</span>, ha <span class="op">=</span> <span class="st">"right"</span>)</span>
<span id="cb75-13"><a href="#cb75-13" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb75-14"><a href="#cb75-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2021-06-01-Employee-Exit-Survey-Data-Cleaning-Aggregation_files/figure-html/cell-45-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Notably, the dissatisfaction rate is:</p>
<ul>
<li>Lowest (20%) among resignees aged 20 or younger.</li>
<li>Above 30% among resignees aged 21 or older.</li>
<li>Highest (42%) among resignees aged 56 or older, 51-55, or 26-30.</li>
</ul>
<p>Let’s group the data further using the institute (DETE or TAFE).</p>
<div class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>table_4 <span class="op">=</span> df.pivot_table(</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>    values <span class="op">=</span> [<span class="st">"dissatisfaction"</span>],</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>    index <span class="op">=</span> [<span class="st">"age"</span>, <span class="st">"institute"</span>],</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>    aggfunc <span class="op">=</span> np.mean, <span class="co"># Mean will determine the percentage of True values. True is 1; False is 0.</span></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>).reset_index()</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>table_4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="45">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">institute</th>
<th data-quarto-table-cell-role="th">dissatisfaction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>20 or younger</td>
<td>DETE</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>20 or younger</td>
<td>TAFE</td>
<td>0.222222</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>21-25</td>
<td>DETE</td>
<td>0.310345</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>21-25</td>
<td>TAFE</td>
<td>0.303030</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>26-30</td>
<td>DETE</td>
<td>0.571429</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>26-30</td>
<td>TAFE</td>
<td>0.250000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>31-35</td>
<td>DETE</td>
<td>0.551724</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>31-35</td>
<td>TAFE</td>
<td>0.218750</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>36-40</td>
<td>DETE</td>
<td>0.390244</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>36-40</td>
<td>TAFE</td>
<td>0.281250</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>41-45</td>
<td>DETE</td>
<td>0.479167</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>41-45</td>
<td>TAFE</td>
<td>0.266667</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>46-50</td>
<td>DETE</td>
<td>0.452381</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>46-50</td>
<td>TAFE</td>
<td>0.307692</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>51-55</td>
<td>DETE</td>
<td>0.593750</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">15</td>
<td>51-55</td>
<td>TAFE</td>
<td>0.282051</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">16</td>
<td>56 or older</td>
<td>DETE</td>
<td>0.551020</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">17</td>
<td>56 or older</td>
<td>TAFE</td>
<td>0.206897</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The table is visualized in the bar graph below.</p>
<div class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>sns.barplot(</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> table_4,</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> <span class="st">"age"</span>,</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> <span class="st">"dissatisfaction"</span>,</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>    hue <span class="op">=</span> <span class="st">"institute"</span>,</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>    estimator <span class="op">=</span> np.mean,</span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>    ci <span class="op">=</span> <span class="va">None</span>,</span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Dissatisfaction Rates of Resignees by Age Group"</span>)</span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Age Group"</span>)</span>
<span id="cb77-12"><a href="#cb77-12" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Percentage of Resignees who were Dissatisfied"</span>)</span>
<span id="cb77-13"><a href="#cb77-13" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation <span class="op">=</span> <span class="dv">30</span>, ha <span class="op">=</span> <span class="st">"right"</span>)</span>
<span id="cb77-14"><a href="#cb77-14" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb77-15"><a href="#cb77-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2021-06-01-Employee-Exit-Survey-Data-Cleaning-Aggregation_files/figure-html/cell-47-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>We can see that employees of DETE generally had much higher dissatisfaction rates than employees of TAFE across all age groups.</p>
<p>The exception is the “20 or younger” age group, which has a 0% dissatisfaction rate for DETE employees. However, this is due to the fact that only one resignee from DETE was 20 years old or younger.</p>
<div class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>    combined</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>    .loc[combined[<span class="st">"institute"</span>] <span class="op">==</span> <span class="st">"DETE"</span>, <span class="st">"age"</span>]</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>    .value_counts()</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>    .sort_index()</span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="47">
<pre><code>20 or younger     1
21-25            29
26-30            35
31-35            29
36-40            41
41-45            48
46-50            42
51-55            32
56 or older      49
Name: age, dtype: int64</code></pre>
</div>
</div>
<p>Thus, we can generally say that the dissatisfaction rate was much higher among DETE resignees compared to TAFE resignees.</p>
<p>Also, the peak dissatisfaction rates occurred in age groups around <strong>26-30 years old and 51-55 years old</strong> for both institutes.</p>
</section>
<section id="dissatisfaction-by-career-stage" class="level2">
<h2 class="anchored" data-anchor-id="dissatisfaction-by-career-stage">Dissatisfaction by Career Stage</h2>
<p>Next, we will determine what percentage of the resignees was dissatisfied with work based on career stage.</p>
<div class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop missing values in specific columns.</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> combined.dropna(subset <span class="op">=</span> [<span class="st">"dissatisfaction"</span>, <span class="st">"service_cat"</span>]).copy()</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Cast booleans to integers.</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"dissatisfaction"</span>] <span class="op">=</span> df[<span class="st">"dissatisfaction"</span>].astype(<span class="bu">int</span>)</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>table_1 <span class="op">=</span> df.pivot_table(</span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>    values <span class="op">=</span> [<span class="st">"dissatisfaction"</span>],</span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>    index <span class="op">=</span> [<span class="st">"service_cat"</span>],</span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a>    aggfunc <span class="op">=</span> np.mean, <span class="co"># Mean will determine the percentage of True values. True is 1; False is 0.</span></span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a>).reset_index()</span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-13"><a href="#cb80-13" aria-hidden="true" tabindex="-1"></a>table_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="48">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">service_cat</th>
<th data-quarto-table-cell-role="th">dissatisfaction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Newbie</td>
<td>0.295337</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Sage</td>
<td>0.485294</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Sophomore</td>
<td>0.343023</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Tenured</td>
<td>0.516129</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The table is visualized in the figure below.</p>
<div class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>sns.barplot(</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> table_1,</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> <span class="st">"service_cat"</span>,</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> <span class="st">"dissatisfaction"</span>,</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>    estimator <span class="op">=</span> np.mean,</span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>    ci <span class="op">=</span> <span class="va">None</span>,</span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Dissatisfaction Rates of Resignees by Career Stage"</span>)</span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Career Stage"</span>)</span>
<span id="cb81-11"><a href="#cb81-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Percentage of Resignees who were Dissatisfied"</span>)</span>
<span id="cb81-12"><a href="#cb81-12" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation <span class="op">=</span> <span class="dv">0</span>)</span>
<span id="cb81-13"><a href="#cb81-13" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb81-14"><a href="#cb81-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2021-06-01-Employee-Exit-Survey-Data-Cleaning-Aggregation_files/figure-html/cell-50-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Interestingly, the dissatisfaction rate is highest (around 50%) within the Tenured and Sage groups of resignees. This is surprising since these are the groups of employees who have been working at the institute for the longest time.</p>
<p>One explanation could be that they became dissatisfied because they spent so much time at the company without career growth or without sufficient variety in their work.</p>
<p>Next, we can group the data further by the specific institute of the employees:</p>
<div class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>table_2 <span class="op">=</span> df.pivot_table(</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>    values <span class="op">=</span> [<span class="st">"dissatisfaction"</span>],</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>    index <span class="op">=</span> [<span class="st">"service_cat"</span>, <span class="st">"institute"</span>], <span class="co"># Group on institute too</span></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>    aggfunc <span class="op">=</span> np.mean,</span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>).reset_index()</span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a>table_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="50">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">service_cat</th>
<th data-quarto-table-cell-role="th">institute</th>
<th data-quarto-table-cell-role="th">dissatisfaction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Newbie</td>
<td>DETE</td>
<td>0.375000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Newbie</td>
<td>TAFE</td>
<td>0.262774</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Sage</td>
<td>DETE</td>
<td>0.560000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Sage</td>
<td>TAFE</td>
<td>0.277778</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Sophomore</td>
<td>DETE</td>
<td>0.460526</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Sophomore</td>
<td>TAFE</td>
<td>0.250000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>Tenured</td>
<td>DETE</td>
<td>0.609756</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>Tenured</td>
<td>TAFE</td>
<td>0.333333</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This table is visualized below.</p>
<div class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>sns.barplot(</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> table_2,</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> <span class="st">"service_cat"</span>,</span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> <span class="st">"dissatisfaction"</span>,</span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>    hue <span class="op">=</span> <span class="st">"institute"</span>,</span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>    estimator <span class="op">=</span> np.mean,</span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>    ci <span class="op">=</span> <span class="va">None</span>,</span>
<span id="cb83-8"><a href="#cb83-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb83-9"><a href="#cb83-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-10"><a href="#cb83-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Dissatisfaction Rates of Resignees by Career Stage"</span>)</span>
<span id="cb83-11"><a href="#cb83-11" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Career Stage"</span>)</span>
<span id="cb83-12"><a href="#cb83-12" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Percentage of Resignees who were Dissatisfied"</span>)</span>
<span id="cb83-13"><a href="#cb83-13" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation <span class="op">=</span> <span class="dv">0</span>)</span>
<span id="cb83-14"><a href="#cb83-14" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb83-15"><a href="#cb83-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="2021-06-01-Employee-Exit-Survey-Data-Cleaning-Aggregation_files/figure-html/cell-52-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The chart shows that the trend is generally consistent between DETE and TAFE. <strong>Tenured and Sage resignees have a higher dissatisfaction rate than other groups.</strong></p>
<p>However, it looks like the dissatisfaction rates in DETE are also much higher than the rates in TAFE. It can be said that dissatisfaction influences the resignation of a greater percentage of people in DETE than it does in TAFE.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>In this project, we worked with 2 datasets of employee exit survey data from the DETE and TAFE government institutes in Australia. We cleaned, transformed, and combined these datasets. Then, we analyzed dissatisfaction rates of resignees based on age and based on career stage.</p>
<p>We found the following notable points:</p>
<ul>
<li>Dissatisfaction rate was highest among resignees in age groups around <strong>26-30 years old and 51-55 years old</strong> for both institutes.</li>
<li>Dissatisfaction rate was highest among resignees who had been working at the institute for <strong>over 7 years</strong>.</li>
<li>The dissatisfaction rate was much <strong>higher among DETE resignees</strong> compared to TAFE resignees. This may have to do with the nature or conditions of the work of DETE employees.</li>
</ul>
<p>Thanks for reading!</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="MiguelAHG/migs-germar-data-science-blog" data-repo-id="R_kgDOJySw9w" data-category="Announcements" data-category-id="DIC_kwDOJySw984CXXr6" data-mapping="pathname" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" data-loading="lazy" async="">
</script>
</div> <!-- /content -->



</body></html>